// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDLPMKENs0VeT8eB5xMqFzVPpqogLfBb4',
    appId: '1:58611301775:web:5d3ab5cf7392011717dffa',
    messagingSenderId: '58611301775',
    projectId: 'push-notification-57cb9',
    authDomain: 'push-notification-57cb9.firebaseapp.com',
    storageBucket: 'push-notification-57cb9.appspot.com',
    measurementId: 'G-9XMWLCPYCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnLSf6-Dtjw-um8zEdaE4fzNbb4SEDFyc',
    appId: '1:58611301775:android:f3e20e163031d6ea17dffa',
    messagingSenderId: '58611301775',
    projectId: 'push-notification-57cb9',
    storageBucket: 'push-notification-57cb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnsyWv6OoVStdbdiQAjZTuWZBZdyUQZmk',
    appId: '1:58611301775:ios:a96e631e377efe5f17dffa',
    messagingSenderId: '58611301775',
    projectId: 'push-notification-57cb9',
    storageBucket: 'push-notification-57cb9.appspot.com',
    iosBundleId: 'com.example.flutterNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnsyWv6OoVStdbdiQAjZTuWZBZdyUQZmk',
    appId: '1:58611301775:ios:e3dacc333f0dca3617dffa',
    messagingSenderId: '58611301775',
    projectId: 'push-notification-57cb9',
    storageBucket: 'push-notification-57cb9.appspot.com',
    iosBundleId: 'com.example.flutterNotifications.RunnerTests',
  );
}
